language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower
- bower install
- node_modules/protractor/bin/webdriver-manager update
script:
- gulp test
addons:
  sauce_connect: true
env:
  global:
  - secure: EgIncGfN2z9rWXRx3y+zHiP16o7vnQw7OZZE+xH0F9c/6iUVfm/+p7E+tZnCRBUktFrZwJBN7r7+52TpLgozYcvGVm9YPPvGHf6sjXo3pJB8k1hxcObf3Kfh2uJNUGFuJ1X8d7Kc1Tz/JYXcbpFWUYwOuC4LO2AIpsXXzeKDM6s=
  - secure: JiYOkGaZuK7FIJoupit9HOZ0rYg6s1H2H3Rkaqu4lkG3HDtIKPO4MD+Uz3cGHdtuB65SPuztj0j6gr+LNq/zAkDKM9F8abKmfBLu6EV4cwSG/0psfYDexudQzTLc3LQCIApD8ao+ceCHrPTXiUCqGHlfVwbdo5FBq2oEUPvLsIU=
