language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: fQziee/7AlK5myB/yO83TMqyQP2TgdKmtrMJk1oycPNkdMU1XuNVUPMlgOeSjpER5ApfxaRwMOwkTa6P15n+sSI+gvhagfDmbKwObFJuWHt7xEPUIzqMPMMsKPzR8QJQGwzJE3gxa+At4NQcRu9CdBLqaR+K+felNATWHf4e9Cw=
  - secure: XNDecwpZ1n5bOUKIK1SNb4bA06di3cOogcF7BK6Zbide7paxQlq5DEfqeVft5i9CQn7nHXjhwGFbv4rR8fbaIBkRbcM06zEHU0KUDOu3pvYjXx+KcaJdmgZbPdEMqPR9aV9Vo6VDfRcUiiKDJOOUAjWTy86VKlesEDesjawpZRM=
before_script:
- npm install -g bower
- bower install
script:
- gulp test
addons:
  sauce_connect: true
